exporters:
    telegraf_cloudwatch: {}
receivers:
    telegraf_cpu: {}
    telegraf_disk: {}
    telegraf_diskio: {}
    telegraf_ethtool: {}
    telegraf_mem: {}
    telegraf_netstat: {}
    telegraf_nvidia_smi: {}
    telegraf_swap: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatch
            processors: []
            receivers:
                - telegraf_ethtool
                - telegraf_mem
                - telegraf_netstat
                - telegraf_nvidia_smi
                - telegraf_swap
                - telegraf_cpu
                - telegraf_disk
                - telegraf_diskio
