exporters:
    awscloudwatchexporter/ace:
        force_flush_interval: 60s
        namespace: CWAgent
        region: us-west-2
    telegraf_cloudwatch: {}
processors:
    cumulativetodeltaprocessor/ace: {}
    telegraf_delta: {}
    telegraf_ec2tagger: {}
receivers:
    telegraf_cpu: {}
    telegraf_disk: {}
    telegraf_diskio: {}
    telegraf_ethtool: {}
    telegraf_mem: {}
    telegraf_netstat: {}
    telegraf_nvidia_smi: {}
    telegraf_swap: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatch
                - awscloudwatchexporter/ace
            processors:
                - telegraf_ec2tagger
                - telegraf_delta
                - cumulativetodeltaprocessor/ace
            receivers:
                - telegraf_diskio
                - telegraf_ethtool
                - telegraf_mem
                - telegraf_netstat
                - telegraf_nvidia_smi
                - telegraf_swap
                - telegraf_cpu
                - telegraf_disk