exporters:
    cloudwatch: {}
processors:
    delta: {}
    ec2tagger: {}
receivers:
    cpu: {}
    disk: {}
    diskio: {}
    ethtool: {}
    mem: {}
    netstat: {}
    nvidia_smi: {}
    swap: {}
service:
    pipelines:
        metrics:
            exporters:
                - cloudwatch
            processors:
                - delta
                - ec2tagger
            receivers:
                - disk
                - diskio
                - ethtool
                - mem
                - netstat
                - nvidia_smi
                - swap
                - cpu