exporters:
    cloudwatch: {}
receivers:
    cpu: {}
    disk: {}
    diskio: {}
    ethtool: {}
    mem: {}
    netstat: {}
    nvidia_smi: {}
    swap: {}
service:
    pipelines:
        metrics:
            exporters:
                - cloudwatch
            processors: []
            receivers:
                - ethtool
                - mem
                - netstat
                - nvidia_smi
                - swap
                - cpu
                - disk
                - diskio
