exporters:
    cloudwatch: {}
processors:
    ec2tagger: {}
receivers:
    disk: {}
    mem: {}
service:
    pipelines:
        metrics:
            exporters:
                - cloudwatch
            processors:
                - ec2tagger
            receivers:
                - disk
                - mem