exporters:
    telegraf_cloudwatch: {}
processors:
    telegraf_ec2tagger: {}
receivers:
    telegraf_disk: {}
    telegraf_mem: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatch
            processors:
                - telegraf_ec2tagger
            receivers:
                - telegraf_disk
                - telegraf_mem