exporters:
    awscloudwatchexporter/ace:
        force_flush_interval: 60s
        namespace: CWAgent
        region: us-east-1
    telegraf_cloudwatch: {}
processors:
    cumulativetodeltaprocessor/ace: {}
    telegraf_ec2tagger: {}
receivers:
    telegraf_disk: {}
    telegraf_mem: {}
service:
    pipelines:
        metrics:
            exporters:
                - awscloudwatchexporter/ace
                - telegraf_cloudwatch
            processors:
                - cumulativetodeltaprocessor/ace
                - telegraf_ec2tagger
            receivers:
                - telegraf_mem
                - telegraf_disk

