exporters:
    awscloudwatch/ace:
        force_flush_interval: 60s
        namespace: CWAgent
        region: us-east-1
processors:
    cumulativetodelta/ace: {}
    telegraf_ec2tagger: {}
receivers:
    telegraf_disk: {}
    telegraf_mem: {}
service:
    pipelines:
        metrics:
            exporters:
                - awscloudwatch/ace
            processors:
                - cumulativetodelta/ace
                - telegraf_ec2tagger
            receivers:
                - telegraf_mem
                - telegraf_disk

