exporters:
    telegraf_cloudwatch: {}
receivers:
    telegraf_disk: {}
    telegraf_mem: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatch
            processors: []
            receivers:
                - telegraf_disk
                - telegraf_mem
