exporters:
    telegraf_cloudwatch: {}
processors: {}
receivers:
    telegraf_socket_listener: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatch
            processors: []
            receivers:
                - telegraf_socket_listener
