exporters:
    awscloudwatch:
        endpoint_override: https://monitoring-fips.us-west-2.amazonaws.com
        force_flush_interval: 1m0s
        max_datums_per_call: 1000
        max_values_per_datum: 5000
        metric_decoration:
            - category: LogicalDisk
              name: '% Idle Time'
              unit: PERCENT
            - category: LogicalDisk
              name: '% Disk Read Time'
              rename: DISK_READ
            - category: Processor
              name: '% Idle Time'
              rename: CPU_IDLE
              unit: PERCENT
        namespace: CWAgent
        region: us-west-2
        resource_to_telemetry_conversion:
            enabled: true
        role_arn: metrics_role_arn_value_test
        rollup_dimensions:
            - - ImageId
            - - InstanceId
              - InstanceType
            - - d1
            - []
    awscloudwatchlogs/emf_logs:
        endpoint: ""
        local_mode: false
        log_group_name: emf/logs/default
        log_retention: 0
        log_stream_name: LOG_STREAM_NAME
        max_retries: 2
        no_verify_ssl: false
        num_workers: 8
        proxy_address: ""
        raw_log: true
        region: ""
        request_timeout_seconds: 30
        resource_arn: ""
        retry_on_failure:
            enabled: true
            initial_interval: 5s
            max_elapsed_time: 5m0s
            max_interval: 30s
        role_arn: ""
        sending_queue:
            queue_size: 5000
extensions: {}
processors:
    batch/emf_logs:
        send_batch_max_size: 0
        send_batch_size: 8192
        timeout: 200ms
    ec2tagger:
        ec2_instance_tag_keys:
            - AutoScalingGroupName
        ec2_metadata_tags:
            - ImageId
            - InstanceId
            - InstanceType
        refresh_interval_seconds: 0s
receivers:
    telegraf_logfile:
        collection_interval: 1m0s
    telegraf_nvidia_smi:
        collection_interval: 1m0s
    telegraf_socket_listener:
        collection_interval: 1m0s
    telegraf_statsd:
        collection_interval: 10s
    telegraf_procstat/1340600742:
        alias_name:          agent
        collection_interval: 1m0s
    telegraf_win_perf_counters/1063858558:
        alias_name:          Network Interface
        collection_interval: 5s
    telegraf_win_perf_counters/1492679118:
        alias_name:          Memory
        collection_interval: 5s
    telegraf_win_perf_counters/2402387132:
        alias_name:          System
        collection_interval: 1m0s
    telegraf_win_perf_counters/3081249416:
        alias_name:          customizedObjectName
        collection_interval: 1m0s
    telegraf_win_perf_counters/3762679655:
        alias_name:          Processor
        collection_interval: 1m0s
    telegraf_win_perf_counters/4283769065:
        alias_name:          LogicalDisk
        collection_interval: 1m0s
    telegraf_windows_event_log:
        collection_interval: 1m0s
    udplog/emf_logs:
        attributes: {}
        encoding: utf-8
        id: udp_input
        listen_address: 127.0.0.1:25888
        multiline:
            line_end_pattern: .^
            line_start_pattern: ""
        operators: []
        output: []
        resource: {}
        storage: null
        type: udp_input
service:
    extensions: []
    pipelines:
        logs/emf_logs:
            exporters:
                - awscloudwatchlogs/emf_logs
            processors:
                - batch/emf_logs
            receivers:
                - udplog/emf_logs
        metrics/host:
            exporters:
                - awscloudwatch
            processors:
                - ec2tagger
            receivers:
                - telegraf_logfile
                - telegraf_nvidia_smi
                - telegraf_socket_listener
                - telegraf_statsd
                - telegraf_procstat/1340600742
                - telegraf_win_perf_counters/1063858558
                - telegraf_win_perf_counters/1492679118
                - telegraf_win_perf_counters/2402387132
                - telegraf_win_perf_counters/3081249416
                - telegraf_win_perf_counters/3762679655
                - telegraf_win_perf_counters/4283769065
                - telegraf_windows_event_log
    telemetry:
        logs:
            development: false
            disable_caller: false
            disable_stacktrace: false
            encoding: console
            error_output_paths: []
            initial_fields: {}
            level: debug
            output_paths:
                - c:\ProgramData\Amazon\AmazonCloudWatchAgent\Logs\amazon-cloudwatch-agent.log
            sampling:
                initial: 2
                thereafter: 500
        metrics:
            address: ""
            level: None
        resource: {}
        traces:
            propagators: []
