exporters:
    awscloudwatch/ace:
        endpoint_override: https://monitoring-fips.us-west-2.amazonaws.com
        force_flush_interval: 60s
        max_datums_per_call: 1000
        max_values_per_datum: 5000
        metric_decoration:
            - category: cpu
              name: usage_idle
              rename: CPU_USAGE_IDLE
              unit: unit
            - category: cpu
              name: usage_nice
              unit: unit
            - category: disk
              name: free
              rename: DISK_FREE
              unit: unit
        namespace: CWAgent
        region: us-west-2
        role_arn: metrics_role_arn_value_test
        rollup_dimensions:
            - - ImageId
            - - InstanceId
              - InstanceType
            - - d1
            - []
processors:
    cumulativetodelta/ace: {}
    telegraf_delta: {}
    telegraf_ec2tagger: {}
receivers:
    telegraf_cpu: {}
    telegraf_disk: {}
    telegraf_diskio: {}
    telegraf_logfile: {}
    telegraf_mem: {}
    telegraf_net: {}
    telegraf_netstat: {}
    telegraf_processes: {}
    telegraf_procstat: {}
    telegraf_socket_listener: {}
    telegraf_statsd: {}
    telegraf_swap: {}
service:
    pipelines:
        metrics:
            exporters:
                - awscloudwatch/ace
            processors:
                - telegraf_ec2tagger
                - telegraf_delta
                - cumulativetodelta/ace
            receivers:
                - telegraf_cpu
                - telegraf_mem
                - telegraf_netstat
                - telegraf_processes
                - telegraf_socket_listener
                - telegraf_disk
                - telegraf_swap
                - telegraf_statsd
                - telegraf_logfile
                - telegraf_procstat
                - telegraf_diskio
                - telegraf_net