exporters:
    telegraf_cloudwatch: {}
    telegraf_cloudwatchlogs: {}
processors:
    telegraf_ec2tagger: {}
receivers:
    telegraf_logfile: {}
    telegraf_nvidia_smi: {}
    telegraf_procstat: {}
    telegraf_socket_listener: {}
    telegraf_statsd: {}
    telegraf_win_perf_counters: {}
    telegraf_windows_event_log: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatchlogs
                - telegraf_cloudwatch
            processors:
                - telegraf_ec2tagger
            receivers:
                - telegraf_win_perf_counters
                - telegraf_nvidia_smi
                - telegraf_procstat
                - telegraf_statsd
                - telegraf_socket_listener
                - telegraf_logfile
                - telegraf_windows_event_log
