exporters:
    telegraf_cloudwatch: {}
    telegraf_cloudwatchlogs: {}
processors:
    telegraf_delta: {}
    telegraf_ec2tagger: {}
receivers:
    telegraf_cpu: {}
    telegraf_disk: {}
    telegraf_diskio: {}
    telegraf_logfile: {}
    telegraf_mem: {}
    telegraf_net: {}
    telegraf_netstat: {}
    telegraf_processes: {}
    telegraf_procstat: {}
    telegraf_socket_listener: {}
    telegraf_statsd: {}
    telegraf_swap: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatchlogs
                - telegraf_cloudwatch
            processors:
                - telegraf_ec2tagger
                - telegraf_delta
            receivers:
                - telegraf_processes
                - telegraf_swap
                - telegraf_mem
                - telegraf_disk
                - telegraf_statsd
                - telegraf_socket_listener
                - telegraf_procstat
                - telegraf_cpu
                - telegraf_logfile
                - telegraf_net
                - telegraf_netstat
                - telegraf_diskio
