exporters:
    cloudwatch: {}
    cloudwatchlogs: {}
processors:
    delta: {}
    ec2tagger: {}
receivers:
    cpu: {}
    disk: {}
    diskio: {}
    logfile: {}
    mem: {}
    net: {}
    netstat: {}
    processes: {}
    procstat: {}
    socket_listener: {}
    statsd: {}
    swap: {}
service:
    pipelines:
        metrics:
            exporters:
                - cloudwatch
                - cloudwatchlogs
            processors:
                - ec2tagger
                - delta
            receivers:
                - cpu
                - socket_listener
                - disk
                - statsd
                - netstat
                - logfile
                - processes
                - diskio
                - mem
                - swap
                - net
                - procstat
