exporters:
  telegraf_aws_csm: {}
processors: {}
receivers:
  telegraf_awscsm_listener: {}
service:
  pipelines:
    metrics:
      exporters:
        - telegraf_aws_csm
      processors: []
      receivers:
        - telegraf_awscsm_listener