exporters:
    telegraf_cloudwatch: {}
processors:
    telegraf_delta: {}
    telegraf_ec2tagger: {}
receivers:
    telegraf_diskio: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatch
            processors:
                - telegraf_ec2tagger
                - telegraf_delta
            receivers:
                - telegraf_diskio