exporters:
    cloudwatch: {}
processors:
    delta: {}
    ec2tagger: {}
receivers:
    diskio: {}
service:
    pipelines:
        metrics:
            exporters:
                - cloudwatch
            processors:
                - ec2tagger
                - delta
            receivers:
                - diskio