exporters: {}
processors: {}
receivers:
    telegraf_logfile: {}
    telegraf_windows_event_log: {}
service:
    pipelines:
        metrics:
            exporters: []
            processors: []
            receivers:
                - telegraf_logfile
                - telegraf_windows_event_log