exporters:
    telegraf_cloudwatchlogs: {}
processors:
    telegraf_emfProcessor: {}
receivers:
    telegraf_prometheus_scraper: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatchlogs
            processors:
                - telegraf_emfProcessor
            receivers:
                - telegraf_prometheus_scraper
