exporters:
    telegraf_cloudwatchlogs: {}
receivers:
    telegraf_prometheus_scraper: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatchlogs
            processors: []
            receivers:
                - telegraf_prometheus_scraper
