exporters:
    awscloudwatch/ace:
        force_flush_interval: 60s
        namespace: CWAgent
        profile: AmazonCloudWatchAgent
        region: us-west-2
        shared_credential_file: fake-path
processors:
    cumulativetodelta/ace: {}
    telegraf_ec2tagger: {}
receivers:
    telegraf_win_perf_counters: {}
service:
    pipelines:
        metrics:
            exporters:
                - awscloudwatch/ace
            processors:
                - telegraf_ec2tagger
                - cumulativetodelta/ace
            receivers:
                - telegraf_win_perf_counters