exporters:
    cloudwatch: {}
processors:
    ec2tagger: {}
receivers:
    win_perf_counters: {}
service:
    pipelines:
        metrics:
            exporters:
                - cloudwatch
            processors:
                - ec2tagger
            receivers:
                - win_perf_counters