exporters:
    cloudwatch: {}
processors:
    delta: {}
    ec2tagger: {}
receivers:
    cpu: {}
    disk: {}
    diskio: {}
    mem: {}
    swap: {}
service:
    pipelines:
        metrics:
            exporters:
                - cloudwatch
            processors:
                - ec2tagger
                - delta
            receivers:
                - diskio
                - mem
                - swap
                - cpu
                - disk