exporters:
    telegraf_cloudwatch: {}
processors:
    telegraf_ec2tagger: {}
receivers:
    telegraf_win_perf_counters: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatch
            processors:
                - telegraf_ec2tagger
            receivers:
                - telegraf_win_perf_counters