exporters:
    awscloudwatch:
        force_flush_interval: 1m0s
        max_datums_per_call: 1000
        max_values_per_datum: 150
        namespace: CWAgent
        region: us-west-2
        resource_to_telemetry_conversion:
            enabled: true
extensions: {}
processors:
    cumulativetodelta/hostDeltaMetrics:
        exclude:
            match_type: strict
            metrics:
                - iops_in_progress
                - diskio_iops_in_progress
            regexp: null
        include:
            match_type: ""
            metrics: []
            regexp: null
        max_staleness: 0s
receivers:
    telegraf_cpu:
        collection_interval: 1m0s
    telegraf_disk:
        collection_interval: 1m0s
    telegraf_diskio:
        collection_interval: 1m0s
    telegraf_mem:
        collection_interval: 1m0s
    telegraf_swap:
        collection_interval: 1m0s
service:
    extensions: []
    pipelines:
        metrics/host:
            exporters:
                - awscloudwatch
            processors: []
            receivers:
                - telegraf_cpu
                - telegraf_disk
                - telegraf_mem
                - telegraf_swap
        metrics/hostDeltaMetrics:
            exporters:
                - awscloudwatch
            processors:
                - cumulativetodelta/hostDeltaMetrics
            receivers:
                - telegraf_diskio
    telemetry:
        logs:
            development: false
            disable_caller: false
            disable_stacktrace: false
            encoding: "json"
            error_output_paths: []
            initial_fields: {}
            level: info
            output_paths: []
        metrics:
            address: ""
            level: none
        resource: {}
        traces:
            propagators: []
