exporters:
    awscloudwatch/ace:
        force_flush_interval: 60s
        namespace: CWAgent
        region: us-west-2
    telegraf_cloudwatch: {}
processors:
    cumulativetodelta/ace: {}
    telegraf_ec2tagger: {}
receivers:
    telegraf_win_perf_counters: {}
service:
    pipelines:
        metrics:
            exporters:
                - awscloudwatch/ace
                - telegraf_cloudwatch
            processors:
                - telegraf_ec2tagger
                - cumulativetodelta/ace
            receivers:
                - telegraf_win_perf_counters