exporters:
    awscloudwatch/ace:
        force_flush_interval: 60s
        namespace: CWAgent
        region: us-west-2
    telegraf_cloudwatch: {}
processors:
    cumulativetodelta/ace: {}
    telegraf_delta: {}
    telegraf_ec2tagger: {}
receivers:
    telegraf_cpu: {}
    telegraf_disk: {}
    telegraf_diskio: {}
    telegraf_mem: {}
    telegraf_swap: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatch
                - awscloudwatch/ace
            processors:
                - cumulativetodelta/ace
                - telegraf_ec2tagger
                - telegraf_delta
            receivers:
                - telegraf_cpu
                - telegraf_disk
                - telegraf_diskio
                - telegraf_mem
                - telegraf_swap