exporters:
    telegraf_cloudwatch: {}
receivers:
    telegraf_win_perf_counters: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatch
            processors: []
            receivers:
                - telegraf_win_perf_counters
