exporters:
    awscloudwatch:
        force_flush_interval: 1m0s
        max_datums_per_call: 1000
        max_values_per_datum: 150
        namespace: CWAgent
        profile: AmazonCloudWatchAgent
        region: us-west-2
        resource_to_telemetry_conversion:
            enabled: true
        shared_credential_file: fake-path
extensions: {}
processors:
    ec2tagger:
        ec2_instance_tag_keys:
            - AutoScalingGroupName
        ec2_metadata_tags:
            - ImageId
            - InstanceId
            - InstanceType
        refresh_interval_seconds: 0s
receivers:
    telegraf_win_perf_counters:
        collection_interval: 1m0s
service:
    extensions: []
    pipelines:
        metrics/host:
            exporters:
                - awscloudwatch
            processors:
                - ec2tagger
            receivers:
                - telegraf_win_perf_counters
    telemetry:
        logs:
            development: false
            disable_caller: false
            disable_stacktrace: false
            encoding: console
            error_output_paths: []
            initial_fields: {}
            level: info
            output_paths: [c:\ProgramData\Amazon\AmazonCloudWatchAgent\Logs\amazon-cloudwatch-agent.log]
            sampling:
                initial: 2
                thereafter: 500
        metrics:
            address: ""
            level: None
        resource: {}
        traces:
            propagators: []
