exporters:
    awscloudwatch/ace:
        force_flush_interval: 60s
        namespace: CWAgent
        region: us-west-2
processors:
    cumulativetodelta/ace: {}
receivers:
    telegraf_statsd: {}
service:
    pipelines:
        metrics:
            exporters:
                - awscloudwatch/ace
            processors:
                - cumulativetodelta/ace
            receivers:
                - telegraf_statsd