exporters:
    awscloudwatchexporter/ace:
        force_flush_interval: 60s
        namespace: CWAgent
        region: us-west-2
    telegraf_cloudwatch: {}
processors:
    cumulativetodeltaprocessor/ace: {}
receivers:
    telegraf_statsd: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatch
                - awscloudwatchexporter/ace
            processors:
                - cumulativetodeltaprocessor/ace
            receivers:
                - telegraf_statsd