exporters:
    awscloudwatch/host:
        force_flush_interval: 1m0s
        max_datums_per_call: 1000
        max_values_per_datum: 150
        namespace: CWAgent
        region: us-west-2
        resource_to_telemetry_conversion:
            enabled: true
extensions: {}
processors:
    cumulativetodelta/host:
        exclude:
            match_type: ""
            metrics: []
            regexp: null
        include:
            match_type: ""
            metrics: []
            regexp: null
        max_staleness: 0s
receivers:
    telegraf_statsd:
        collection_interval: 10s
service:
    extensions: []
    pipelines:
        metrics/host:
            exporters:
                - awscloudwatch/host
            processors:
                - cumulativetodelta/host
            receivers:
                - telegraf_statsd
    telemetry:
        logs:
            development: false
            disable_caller: false
            disable_stacktrace: false
            encoding: "json"
            error_output_paths: []
            initial_fields: {}
            level: info
            output_paths: []
        metrics:
            address: ""
            level: none
        resource: {}
        traces:
            propagators: []
