exporters:
    cloudwatch: {}
processors: {}
receivers:
    statsd: {}
service:
    pipelines:
        metrics:
            exporters:
                - cloudwatch
            processors: []
            receivers:
                - statsd
