exporters:
    telegraf_cloudwatch: {}
receivers:
    telegraf_statsd: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatch
            processors: []
            receivers:
                - telegraf_statsd
