exporters:
    telegraf_cloudwatchlogs: {}
processors: {}
receivers:
    telegraf_windows_event_log: {}
service:
    pipelines:
        metrics:
            exporters:
                - telegraf_cloudwatchlogs
            processors: []
            receivers:
                - telegraf_windows_event_log
