name: Upload Nightly Binaries
env:
  TERRAFORM_AWS_ASSUME_ROLE: ${{ secrets.TERRAFORM_AWS_ASSUME_ROLE }}
  S3_INTEGRATION_BUCKET: ${{ secrets.S3_INTEGRATION_BUCKET }}

on:
  schedule:
    - cron: '0 0 * * *' # run at midnight
  workflow_dispatch:

jobs:

  build:
    name: Upload Nightly Binaries
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ~1.19.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-west-2

      #Need to install rpm so ubuntu can make rpm by default ubuntu can make deb
      - name: Install rpm
        run: sudo apt install rpm

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Release
        run: make nightly-release

      - name: Upload to S3
        run: aws s3 cp build/bin s3://${S3_INTEGRATION_BUCKET}/nightly-build/latest/ --recursive --acl public-read --source-region us-east-1

      # Users should only take the tar of the darwin build according to our readme so deleting this does not matter. More of a sanity step
      - name: Delete Mac Binary As This Should Only Be Built On Mac
        run: |
          aws s3 rm --recursive s3://${S3_INTEGRATION_BUCKET}/nightly-build/latest/darwin_amd64/
          aws s3 rm --recursive s3://${S3_INTEGRATION_BUCKET}/nightly-build/latest/darwin_arm64/

  mac-build:
    name: Upload Mac Nightly Binaries
    runs-on: macos-11
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ~1.19.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-west-2

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Mac nightly release
        run: make nightly-release-mac

      - name: Upload to S3
        run: aws s3 cp build/bin/darwin s3://${S3_INTEGRATION_BUCKET}/nightly-build/latest/darwin/ --recursive --acl public-read --source-region us-east-1
