name: Upload Nightly Binaries
env:
  TERRAFORM_AWS_ASSUME_ROLE: ${{ secrets.TERRAFORM_AWS_ASSUME_ROLE }}
  S3_INTEGRATION_BUCKET: ${{ secrets.S3_INTEGRATION_BUCKET }}

on:
  schedule:
    - cron: '0 0 * * *' # run at midnight
  workflow_dispatch:

jobs:
  BuildAndUpload:
    uses: ./.github/workflows/test-build.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      ContainerRepositoryNameAndTag: "nightly-build:latest"
      BucketKey: "nightly-build/latest"

  MakeMacPkg:
    name: 'MakeMacPkg'
    runs-on: macos-11
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ~1.19.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-east-1

      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: |
              ~/Library/Caches/go-build
              ~/go/pkg/mod
          key: v1-go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}


      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mac nightly release
        run: make nightly-release-mac

      - name: Upload to S3
        run: aws s3 cp build/bin/darwin s3://${S3_INTEGRATION_BUCKET}/nightly-build/latest/darwin/ --recursive --acl public-read --source-region us-east-1
