# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: NonProd Release
env:
  TERRAFORM_AWS_ASSUME_ROLE: ${{ secrets.TERRAFORM_AWS_ASSUME_ROLE }}
  S3_INTEGRATION_BUCKET: ${{ secrets.S3_INTEGRATION_BUCKET }}

on:
  workflow_call:
  workflow_dispatch:

jobs:
  BuildAndUpload:
    name: "BuildAndUpload"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      # This is a workaround to fix an issue where "git describe" was failing when running the action on my fork.
      # https://github.com/actions/checkout/issues/206
      - run: |
          git fetch --prune --unshallow --tags
          echo exit code $?
          git tag --list
          git describe --tag --dirty

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-west-2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ~1.19.2

      - name: Cache go
        id: cached_go
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: v1-go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      # Required to build rpm again to reset cw agent version to new tag version
      - name: Build RPM
        run: make amazon-cloudwatch-agent-linux package-rpm package-deb

      - name: Copy RPM To nonprod
        run: |
          aws s3 cp build/bin/linux/amd64/amazon-cloudwatch-agent.rpm s3://${S3_INTEGRATION_BUCKET}/nonprod/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
          aws s3 cp build/bin/linux/amd64/amazon-cloudwatch-agent.rpm s3://${S3_INTEGRATION_BUCKET}/nonprod/amazon_linux/amd64/latest/amazon-cloudwatch-agent.deb
          aws s3 cp build/bin/linux/arm64/amazon-cloudwatch-agent.rpm s3://${S3_INTEGRATION_BUCKET}/nonprod/amazon_linux/arm64/latest/amazon-cloudwatch-agent.rpm
          aws s3 cp build/bin/linux/arm64/amazon-cloudwatch-agent.rpm s3://${S3_INTEGRATION_BUCKET}/nonprod/amazon_linux/arm64/latest/amazon-cloudwatch-agent.deb
          aws s3 cp build/bin/CWAGENT_VERSION s3://${S3_INTEGRATION_BUCKET}/nonprod/CWAGENT_VERSION

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

        # QEMU is an open-source machine emulator and virtualizer.
        # It allows users to build ARM CUDA binaries on their x86 machine without needing a cross-compiler.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Build dir is ignored in our .dockerignore thus need to copy to another dir.
      - name: Copy Binary For Agent Image Build
        run: cp -r build/bin/linux/* .

      # Documentation: https://github.com/docker/build-push-action
      - name: Build Cloudwatch Agent Image
        uses: docker/build-push-action@v2
        with:
          file: amazon-cloudwatch-container-insights/cloudwatch-agent-dockerfile/localdeb/Dockerfile
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/ccwa_nonprod:latest
          platforms: linux/amd64, linux/arm64
